[mcp_servers.local-lm-cli]
command = "node"
args = ["/Users/eightman/Desktop/software_develop/mcp-local_lm-cli/dist/index.js"]

[mcp_servers.serena]
command = "uvx"
args = [
    "--from",
    "git+https://github.com/oraios/serena",
    "serena",
    "start-mcp-server",
    "--context",
    "ide-assistant",
    "--project",
    "/Users/eightman/dev/hoi4/HOI4-Bakasekaitizu-MOD",
]
