NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 3.3
NDefines.NAir.NAVAL_STRIKE_CARRIER_MULTIPLIER = 3.3
NDefines.NNavy.CARRIER_STACK_PENALTY = 10
NDefines.NNavy.CARRIER_STACK_PENALTY_EFFECT = 0.08
NDefines.NAI.CARRIER_TASKFORCE_MAX_CARRIER_COUNT = 10
